# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    steps:
    
    - task: DownloadSecureFile@1
      displayName: 'download EU backendend'
      inputs:
        secureFile: 'BACKEND_ENV_FILE_EU' # string. Required. Secure File. 

    - task: CopyFiles@2
      displayName: 'copy EU backendend'
      inputs:
        SourceFolder: '$(Agent.TempDirectory)'
        Contents: BACKEND_ENV_FILE_EU
        TargetFolder: './backend'

    - script: mv ./backend/BACKEND_ENV_FILE_EU ./backend/.env
      displayName: 'rename eu .env'
    - task: DownloadSecureFile@1
      displayName: 'download eu frontend'
      inputs:
        secureFile: 'FRONTEND_ENV_FILE_EU' # string. Required. Secure File. 

    - task: CopyFiles@2
      displayName: 'copy eu frontend'
      inputs:
        SourceFolder: '$(Agent.TempDirectory)'
        Contents: FRONTEND_ENV_FILE_EU
        TargetFolder: './frontend'

    - script: mv ./frontend/FRONTEND_ENV_FILE_EU ./frontend/.env
      displayName: 'rename eu .env'

    - script: ls -a ./frontend
      displayName: 'ls' 

    - script: ls -Rn
      displayName: 'ls'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

  - deployment: VMDeploy
    dependsOn: Build
    displayName: Web deploy
    environment:
      name:  TEST
      resourceType: VirtualMachine
    strategy:
      runOnce:
        preDeploy:
            steps:
            - download: current
              artifact: drop
            - script: echo initialize, cleanup, backup, install certs
        
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Modify deployment script based on the app type
                echo "Starting deployment script run"
               

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              destinationFolder: '$(Pipeline.Workspace)/japp' 
              cleanDestinationFolder: true 
              overwriteExistingFiles: true
              #pathToSevenZipTool: # string. Path to 7z utility.

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                nvm use 12.20.1
                node -v
                npm install
                npm run build
              #pm2 restart index
              #systemctl reload nginx
             

        routeTraffic:
          steps:
          - script: echo routing traffic
        postRouteTraffic:
          steps:
          - script: echo health check post-route traffic
        on:
          failure:
            steps:
            - script: echo Restore from backup! This is on failure
          success:
            steps:
            - script: echo Notify! This is on success
              
     

      