# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- einoSTAG

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.20.1'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'
  
- task: CopyFilesOverSSH@0
  inputs:
      sshEndpoint: junctionAppEurope# string. Required. SSH service connection. 
      sourceFolder: /backend/build # string. Source folder. 
      contents: '**' # string. Required. Contents. Default: **.
      targetFolder: /usr/share/nginx/html/build # string. Target folder. 
    # Advanced
      #isWindowsOnTarget: false # boolean. Target machine running Windows. Default: false.
      cleanTargetFolder: true # boolean. Clean target folder. Default: false.
      #cleanHiddenFilesInTarget: false # boolean. Optional. Use when cleanTargetFolder = true. Remove hidden files in target folder. Default: false.
      readyTimeout: '20000' # string. Required. SSH handshake timeout. Default: 20000.
      #overwrite: true # boolean. Overwrite. Default: true.
      #failOnEmptySource: false # boolean. Fail if no files found to copy. Default: false.
      #flattenFolders: false # boolean. Flatten folders. Default: false.
      