# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.20.1'
  displayName: 'Install Node.js'

#- script: |
 #   npm install
  #displayName: 'npm install'

- script: ls -R
  displayName: 'ls'

# - task: DownloadSecureFile@1
#   displayName: 'download EU backendend'
#   inputs:
#     secureFile: 'BACKEND_ENV_FILE_EU' # string. Required. Secure File. 

# - task: CopyFiles@2
#   displayName: 'copy EU backendend'
#   inputs:
#     SourceFolder: '$(Agent.TempDirectory)'
#     Contents: BACKEND_ENV_FILE_EU
#     TargetFolder: './backend'

# - script: mv ./backend/BACKEND_ENV_FILE_EU ./backend/.env
#   displayName: 'rename eu .env'
# - task: DownloadSecureFile@1
#   displayName: 'download eu frontend'
#   inputs:
#     secureFile: 'FRONTEND_ENV_FILE_EU' # string. Required. Secure File. 

# - task: CopyFiles@2
#   displayName: 'copy eu frontend'
#   inputs:
#     SourceFolder: '$(Agent.TempDirectory)'
#     Contents: FRONTEND_ENV_FILE_EU
#     TargetFolder: './frontend'

# - script: ls frontend -a
#   displayName: 'ls'

# - script: mv ./frontend/FRONTEND_ENV_FILE_EU ./frontend/.env
#   displayName: 'rename eu .env'

# - script: ls -a ./frontend
#   displayName: 'ls'

# - script: cat ./frontend/.env
#   displayName: 'cat'

# - script: |
#     npm install
#   displayName: 'install frontend'

# - script: |
#     cd frontend && npm install
#   displayName: 'npm setup front'

  
# - script: |
#     rm -rf ./backend/build && cd frontend && npm run build && cp -r ./build ../backend/build
#   displayName: 'npm build front'

# - script: rm -rf ./frontend/node_modules
#   displayName: 'rm frontend node_modules'

# - script: ls -R
#   displayName: 'ls'


#- task: CopyFilesOverSSH@0
#  inputs:
#      sshEndpoint: 'newadmin_junctionappeurope'
#      sourceFolder: '.'
#      contents: '**' 
#      targetFolder: '/home/newadmin/build'
#    # Advanced
#      #isWindowsOnTarget: false # boolean. Target machine running Windows. Default: false.
#      cleanTargetFolder: true 
#      #cleanHiddenFilesInTarget: false # boolean. Optional. Use when cleanTargetFolder = true. Remove hidden files in target folder. Default: false.
#      #readyTimeout: '20000' 
#      overwrite: true 
#      #failOnEmptySource: false # boolean. Fail if no files found to copy. Default: false.
#      #flattenFolders: false # boolean. Flatten folders. Default: false.

- task: DownloadSecureFile@1
  displayName: 'download backendend'
  inputs:
    secureFile: 'BACKEND_ENV_FILE_ASIA' # string. Required. Secure File. 

- task: CopyFiles@2
  displayName: 'copy backendend'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: BACKEND_ENV_FILE_ASIA
    TargetFolder: './backend'

- script: mv ./backend/BACKEND_ENV_FILE_ASIA ./backend/.env
  displayName: 'rename'
- task: DownloadSecureFile@1
  displayName: 'download frontend'
  inputs:
    secureFile: 'FRONTEND_ENV_FILE_ASIA' # string. Required. Secure File. 

- task: CopyFiles@2
  displayName: 'copy frontend'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: FRONTEND_ENV_FILE_ASIA
    TargetFolder: './frontend'

- script: ls frontend -a
  displayName: 'ls'

- script: mv ./frontend/FRONTEND_ENV_FILE_ASIA ./frontend/.env
  displayName: 'rename'

- script: |
    npm install
  displayName: 'install frontend'

- script: |
    cd frontend && npm install
  displayName: 'npm setup front'

  
- script: |
    rm -rf ./backend/build && cd frontend && npm run build && cp -r ./build ../backend/build
  displayName: 'npm build front'


- script: rm -rf ./frontend/node_modules
  displayName: 'rm frontend'

- script: rm -rf ./node_modules
  displayName: 'rm node_modules'

- script: ls -R
  displayName: 'ls'
  
- task: CopyFilesOverSSH@0
  inputs:
      sshEndpoint: 'newadmin_junctionappasia'
      sourceFolder: '.'
      contents: '**' 
      targetFolder: '/home/newadmin/build'
    # Advanced
      #isWindowsOnTarget: false # boolean. Target machine running Windows. Default: false.
      cleanTargetFolder: true 
      #cleanHiddenFilesInTarget: false # boolean. Optional. Use when cleanTargetFolder = true. Remove hidden files in target folder. Default: false.
      #readyTimeout: '20000' 
      overwrite: true 
      #failOnEmptySource: false # boolean. Fail if no files found to copy. Default: false.
      #flattenFolders: false # boolean. Flatten folders. Default: false.
      
- task: SSH@0
  inputs:
    sshEndpoint: 'newadmin_junctionappasia'
    runOptions: 'commands' 
    commands: mkdir /home/newadmin/testdir
    #interactiveSession: true

- task: DownloadSecureFile@1
  displayName: 'download backendend'
  inputs:
    secureFile: 'BACKEND_ENV_FILE_AFRICA' # string. Required. Secure File. 

- task: CopyFiles@2
  displayName: 'copy backendend'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: BACKEND_ENV_FILE_AFRICA
    TargetFolder: './backend'

- script: mv ./backend/BACKEND_ENV_FILE_AFRICA ./backend/.env
  displayName: 'rename'
- task: DownloadSecureFile@1
  displayName: 'download frontend'
  inputs:
    secureFile: 'FRONTEND_ENV_FILE_AFRICA' # string. Required. Secure File. 

- task: CopyFiles@2
  displayName: 'copy frontend'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: FRONTEND_ENV_FILE_AFRICA
    TargetFolder: './frontend'

- script: ls frontend -a
  displayName: 'ls'

- script: mv ./frontend/FRONTEND_ENV_FILE_AFRICA ./frontend/.env
  displayName: 'rename'

- script: |
    npm install
  displayName: 'install frontend'

- script: |
    cd frontend && npm install
  displayName: 'npm setup front'

  
- script: |
    rm -rf ./backend/build && cd frontend && npm run build && cp -r ./build ../backend/build
  displayName: 'npm build front'

- script: rm -rf ./frontend/node_modules
  displayName: 'rm frontend'



#- task: CopyFilesOverSSH@0
 # inputs:
  #    sshEndpoint: 'newadmin_junctionappafrica'
   #   sourceFolder: '.'
    #  contents: '**' 
     # targetFolder: '/home/newadmin/build'
    # Advanced
      #isWindowsOnTarget: false # boolean. Target machine running Windows. Default: false.
      #cleanTargetFolder: true 
      #cleanHiddenFilesInTarget: false # boolean. Optional. Use when cleanTargetFolder = true. Remove hidden files in target folder. Default: false.
      #readyTimeout: '20000' 
      #overwrite: true 
      #failOnEmptySource: false # boolean. Fail if no files found to copy. Default: false.
      #flattenFolders: false # boolean. Flatten folders. Default: false.

